### ISSUE TITLE
An error occurred while saving the file.

### ISSUE THREAD

**Issue by bittoh** [TheRealYunix/Flipnote-Signer#1]
When attempting to save a Flipnote, a dialogue box appears that says "An error occurred while saving the file." I haven't been able to get the program to save anything correctly yet.

System info:
Windows 11 Education 64-Bit
13th Gen Intel Core i9-13900KF 3.00 GHz
64.0 GB RAM

**Comment by TheRealYunix** [comment]
Thanks for reporting this issue! I'm working on fixing it as quickly as possible. I apologize for the inconvenience. Your feedback is very helpful in resolving this problem.
