### ISSUE TITLE
Missing “windows.h” from ver 0.6 source code

### ISSUE THREAD

**Issue by plotonnn** [TheRealYunix/Flipnote-Signer#2]
I was trying to compile the program on Linux.
When commanded “make main” in any of the folders in the .zip/.tar.gz, there is the same error:

fatal error: windows.h: no such file or directory.
3| #include <windows.h>

**Comment by TheRealYunix** [comment]
Hello plotonnn,
This program only runs under Windows because it uses WinApi32. There are no compilation options for Linux.
