### ISSUE TITLE
add this to the description

### ISSUE THREAD

**Issue by CubeFun** [TheRealYunix/Flipnote-Signer#3]
Hi, so recently i used this tool to sign my flipnote, everything worked well until u uploadedd it to sudomemo and my account for some reason was banned. Just add this disclaimer to the description to warn other people

**Comment by TheRealYunix** [comment]
Hi,

Thank you for bringing this to my attention. I want to clarify that Flipnote Signer is a general tool designed to modify Flipnote files, and it is not intended or optimized specifically for use on Sudomemo or any other platform. There is no mention of Sudomemo in the repository.

Regarding your account issue, Sudomemo’s terms of service clearly state that any content not originally created within the Flipnote Studio software on a Nintendo DSi or 3DS is not allowed. It seems the problem may have arisen from this policy, as our tool does enable modifications that might not comply with those terms.
